name: the_180_project
description: A high-performance calisthenics app for HSPU training.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  provider: ^6.1.1
  camera: ^0.11.0
  video_player: ^2.8.1
  audioplayers: ^6.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
